---
- name: UFW update and restart
  hosts: all
  become: yes

  tasks:
   - name: UFW update to latest
     apt:
      name: ufw
      state: latest
     notify:
      - Restart UFW

  handlers:
   - name: Restart UFW
     service:
      name: ufw
      state: restarted
